<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AbsensiTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('absensi')->insert([
            [
                'id' => 62,
                'data_karyawan_id' => 1,
                'nama' => 'A. Yusril Mahendra',
                'divisi_id' => 1,
                'jumlah_hadir' => 27,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 63,
                'data_karyawan_id' => 2,
                'nama' => 'Abd Rahman',
                'divisi_id' => 4,
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 64,
                'data_karyawan_id' => 3,
                'nama' => 'Adam Achmad Labisa',
                'divisi_id' => 4,
                'jumlah_hadir' => 5,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 65,
                'data_karyawan_id' => 4,
                'nama' => 'Ade Ratih',
                'divisi_id' => 12,
                'jumlah_hadir' => 24,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 66,
                'data_karyawan_id' => 5,
                'nama' => 'Ahmad Dani',
                'divisi_id' => 2,
                'jumlah_hadir' => 13,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 67,
                'data_karyawan_id' => 6,
                'nama' => 'Ahmad Sodiqin',
                'divisi_id' => 3,
                'jumlah_hadir' => 9,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 68,
                'data_karyawan_id' => 7,
                'nama' => 'Akmal',
                'divisi_id' => 1,
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 69,
                'data_karyawan_id' => 8,
                'nama' => 'Ali Akbar',
                'divisi_id' => 8,
                'jumlah_hadir' => 27,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 70,
                'data_karyawan_id' => 9,
                'nama' => 'Andi Rivaldi',
                'divisi_id' => 3,
                'jumlah_hadir' => 12,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 71,
                'data_karyawan_id' => 10,
                'nama' => 'Apriliani Kartika Sari Ali',
                'divisi_id' => 2,
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 72,
                'data_karyawan_id' => 11,
                'nama' => 'Asriana Fitria Auliana Syam',
                'divisi_id' => 2,
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 73,
                'data_karyawan_id' => 12,
                'nama' => 'Ayu Meylani',
                'divisi_id' => 2,
                'jumlah_hadir' => 4,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 74,
                'data_karyawan_id' => 13,
                'nama' => 'Bambang Wiranata',
                'divisi_id' => 4,
                'jumlah_hadir' => 29,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 75,
                'data_karyawan_id' => 14,
                'nama' => 'Erawasi',
                'divisi_id' => 2,
                'jumlah_hadir' => 4,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            // Data berikut tidak ada di DataKaryawanTableSeeder, jadi dikomentari
            // [
            //     'id' => 76,
            //     'data_karyawan_id' => 15,
            //     'nama' => 'Fadli. M',
            //     'divisi_id' => 11,
            //     'jumlah_hadir' => 5,
            //     'mulai' => null,
            //     'berakhir' => null,
            //     'created_at' => '2024-09-10 08:10:06',
            //     'updated_at' => '2024-09-10 08:10:06',
            // ],
            // Tambahkan data lainnya sesuai dengan data di DataKaryawanTableSeeder
        ]);
    }
}
